### ISSUE TITLE
Fix: After initializing the game account

### ISSUE THREAD

**Issue by nlok5923** [RizeLabs/aze-cli#10]
We should do a couple of things

- Highlight the game account id (since this would need to be shared) and web socket url
- Do not show the fail note consumption
<img width="1027" alt="image" src="https://github.com/RizeLabs/aze-cli/assets/56120084/a4bc48ad-ba79-4491-896d-75d2ebf6bd93">

**Comment by nlok5923** [comment]
Just to add this error seems recurrning, I'm not sure which notes it's trying to consume.

**Comment by Created-for-a-purpose** [comment]
These notes are consumable by player account only, since you are using the same client, that's why it is being displayed here.

**Comment by nlok5923** [comment]
Hmm, we should take this to miden team sometime that `get_consume_notes_id` also returns the origin notes as well. Can we atleast somehow suppress the error (not show in logs)

**Comment by Created-for-a-purpose** [comment]
Yes, will fix it.
