### ISSUE TITLE
Fix: On making any actions its giving this error of negative balance.

### ISSUE THREAD

**Issue by nlok5923** [RizeLabs/aze-cli#13]
<img width="861" alt="image" src="https://github.com/RizeLabs/aze-cli/assets/56120084/79ec5952-6f30-4317-9a9a-e16ad6fb7683">

**Comment by Created-for-a-purpose** [comment]
That is because I haven't added fund account before making action, because I thought we are going to fund accounts beforehand so that execution time is minimized.

**Comment by nlok5923** [comment]
I thought while creating the account itself we are funding it. (but makes sense if the game account expects token from some other faucets)
