### ISSUE TITLE
Feat: Can we show which notes are getting consumed 

### ISSUE THREAD

**Issue by nlok5923** [RizeLabs/aze-cli#15]
<img width="512" alt="image" src="https://github.com/RizeLabs/aze-cli/assets/56120084/cb6d026d-3ad9-41a2-a48e-91989ffbbd74">

**Comment by Created-for-a-purpose** [comment]
Do you mean showing note id?

**Comment by nlok5923** [comment]
For example: Received and consuming encrypted card note

**Comment by Created-for-a-purpose** [comment]
I don't think we can do this.

**Comment by nlok5923** [comment]
Closing this as notes aren't that descriptive and should be a major effort issue if we wanna work on it.
