### ISSUE TITLE
Feat: Shuffle card before setting into game account in `plaintext` version of the game

### ISSUE THREAD

**Issue by nlok5923** [RizeLabs/aze-cli#27]

**Comment by Created-for-a-purpose** [comment]
Could you give some details about this? Like what parameters would be required? How exactly would we have a somewhat non-detereministic shuffle?

**Comment by nlok5923** [comment]
it's just that since which initializing game account we are sort of storing the cards in the serial manner. instead we should first maybe randomize the order of cards a bit and then initialize the game account storage with it.
