### ISSUE TITLE
Fix: No of consumable notes by game id turns out to be four 

### ISSUE THREAD

**Issue by nlok5923** [RizeLabs/aze-cli#29]
<img width="595" alt="image" src="https://github.com/RizeLabs/aze-cli/assets/56120084/e5e5dc48-908d-4970-9b62-e9cded21ecdf">

branch: `v-plaintext`
command: `cargo run --release consume-notes -p <player-id> -g <game-id>`

PS: consume-notes run by the player who initiated the game.

**Comment by nlok5923** [comment]
It seems like `client.get_consumable_notes` doesn't even filter note based on account id

**Comment by nlok5923** [comment]
As in other player account stores it says consumable accounts 1 
<img width="550" alt="image" src="https://github.com/RizeLabs/aze-cli/assets/56120084/861043d4-d28c-497f-bdaa-97f115a26ada">

**Comment by nlok5923** [comment]
Seems like #31 could be a fix for this

**Comment by Created-for-a-purpose** [comment]
Player accounts need to be initialized in a separate terminal with a separate client.

**Comment by nlok5923** [comment]
Ohhk, is that decided from the start because i was under the assumption that there would be a main player who will initiate his player account + aze account both at once.

if yes then we can close #31

**Comment by Created-for-a-purpose** [comment]
Yes, since player account will consume all the notes meant for other players if the client was the same as of game account.

**Comment by nlok5923** [comment]
Makes sense then let's close this as well as #31
