### ISSUE TITLE
Fix: Not able to fold by player 3

### ISSUE THREAD

**Issue by nlok5923** [RizeLabs/aze-cli#51]
p1 -> small
p2 -> big
p3 -> call
p4 -> fold
p1 -> raise (10)
p2 -> call
p3 -> fold

<img width="433" alt="image" src="https://github.com/RizeLabs/aze-cli/assets/56120084/77840e8b-bff1-4f00-855f-dc94a690b23c">

**Comment by nlok5923** [comment]
Should highest bet be 15 ? i think it should be 10

<img width="350" alt="image" src="https://github.com/RizeLabs/aze-cli/assets/56120084/ebd0958b-ebd2-47cb-84a5-b7dcfd2e9137">

following the same procedure defined above seems like the logic for setting highest amount in raise procedure is incorrect.

cc @Created-for-a-purpose

**Comment by nlok5923** [comment]
Reproduced it 

Seems like some issue at the procedure end 

This note is for making fold action for player 3

<img width="337" alt="image" src="https://github.com/RizeLabs/aze-cli/assets/56120084/67c24c93-02e5-465f-b32b-9aa898337f0f">

**Comment by Created-for-a-purpose** [comment]
I am also facing these, taking a look.

**Comment by Created-for-a-purpose** [comment]
> Should highest bet be 15 ? i think it should be 10
> 
> <img alt="image" width="350" src="https://private-user-images.githubusercontent.com/56120084/343307546-ebd0958b-ebd2-47cb-84a5-b7dcfd2e9137.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NjUxMDIsIm5iZiI6MTcxOTQ2NDgwMiwicGF0aCI6Ii81NjEyMDA4NC8zNDMzMDc1NDYtZWJkMDk1OGItZWJkMi00N2NiLTg0YTUtYjdkY2ZkMmU5MTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA1MDY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjODE0MDI5MTllMDQwNzc3YjMwMzI4ODQ4MjhiNjUyZGQ5MDQ2Y2NlY2U2YWQwMTgwOGU3MWUwYjAwYThlNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JNxAxC8UxgjtQp-QY5l63MZuolqIWAFNmhzzQuAFOA0">
> following the same procedure defined above seems like the logic for setting highest amount in raise procedure is incorrect.
> 
> cc @Created-for-a-purpose

Also I think it should be 20. Picture this:

Player        Action     Highest bet
    1             Small             5
    2             Big               10
    3             Raise(10)      20

**Comment by nlok5923** [comment]
The actual raise amount would be 5 in big blind case right ? (Like the one which is calculated in procedure)

**Comment by Created-for-a-purpose** [comment]
Raise amount would be 5 no doubt, but highest bet would be 10

**Comment by nlok5923** [comment]
Got it but anyways the player p2 if he makes a call move he needs to bet 10 token

**Comment by Created-for-a-purpose** [comment]
On call, the bet amount = highest bet - player's last bet
