### ISSUE TITLE
Feat: Make the game account onchain accounts, Basically making the account type of those accounts Onchain.

### ISSUE THREAD

**Issue by nlok5923** [RizeLabs/aze-cli#67]

**Comment by Created-for-a-purpose** [comment]
Actually all accounts are OnChain already, the parameter of type `AccountStorageMode` below does not have any effect on storage mode. 
[No use of account_storage_mode: AccountStorageMode](https://github.com/RizeLabs/aze-cli/blob/32bddcc6297ba76ba00364b997ed66ddc7bdffbd/lib/src/client/mod.rs#L593C9-L593C29)

This is the actual storage type implementation:
[Onchain storage mode](https://github.com/RizeLabs/aze-cli/blob/32bddcc6297ba76ba00364b997ed66ddc7bdffbd/lib/src/accounts/mod.rs#L240)

Btw, changed this argument to type `OnChain`:
[Link](https://github.com/RizeLabs/aze-cli/blob/32bddcc6297ba76ba00364b997ed66ddc7bdffbd/cli/src/accounts/mod.rs#L60)

**Comment by nlok5923** [comment]
Using miden-client cli while creating accounts we mention it onchain like this

`miden new-wallet --storage-type on-chain`

Can you check it's implementation and make changes  the way it is done in `miden-client` for creating onchain accounts.

**Comment by Created-for-a-purpose** [comment]
The implementation is already the same for both

**Comment by nlok5923** [comment]
> Link

ig you haven't pushed this changes

**Comment by nlok5923** [comment]
> Actually all accounts are OnChain already, the parameter of type `AccountStorageMode` below does not have any effect on storage mode. [No use of account_storage_mode: AccountStorageMode](https://github.com/RizeLabs/aze-cli/blob/32bddcc6297ba76ba00364b997ed66ddc7bdffbd/lib/src/client/mod.rs#L593C9-L593C29)
> 
> This is the actual storage type implementation: [Onchain storage mode](https://github.com/RizeLabs/aze-cli/blob/32bddcc6297ba76ba00364b997ed66ddc7bdffbd/lib/src/accounts/mod.rs#L240)
> 
> Btw, changed this argument to type `OnChain`: [Link](https://github.com/RizeLabs/aze-cli/blob/32bddcc6297ba76ba00364b997ed66ddc7bdffbd/cli/src/accounts/mod.rs#L60)

ig you haven't pushed this changes.

you can close this issue once the changes are pushed.

**Comment by nlok5923** [comment]
Closing this issue since the changes are pushed!
